packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  "@tanstack/react-query": ^5.90.12
  "@orpc/server": ^1.12.2
  "@orpc/client": ^1.12.2
  "@orpc/openapi": ^1.12.2
  "@orpc/zod": ^1.12.2
  "@orpc/tanstack-query": ^1.12.2
  drizzle-orm: ^0.45.1
  "@types/pg": ^8.15.6
