packages:
  - apps/*
  - packages/*

catalog:
  '@orpc/client': ^1.12.2
  '@orpc/openapi': ^1.12.2
  '@orpc/server': ^1.12.2
  '@orpc/tanstack-query': ^1.12.2
  '@orpc/zod': ^1.12.2
  '@tanstack/react-query': ^5.90.12
  '@types/pg': ^8.15.6
  dotenv: ^17.2.2
  drizzle-orm: ^0.45.1
  typescript: ^5.9.3
  zod: ^4.1.13

onlyBuiltDependencies:
  - esbuild
  - msw
